// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvzR9tGsyuZE3xq-iMAtA12Gn2X2pk1-0',
    appId: '1:12606355560:web:641b36cc23c9e49809a3dd',
    messagingSenderId: '12606355560',
    projectId: 'messenger-clone-fltr',
    authDomain: 'messenger-clone-fltr.firebaseapp.com',
    storageBucket: 'messenger-clone-fltr.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRUO-S5AMY5Y1C1GPPpt6IoZRIwyp-klM',
    appId: '1:12606355560:android:1999afb3131fd0af09a3dd',
    messagingSenderId: '12606355560',
    projectId: 'messenger-clone-fltr',
    storageBucket: 'messenger-clone-fltr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDITrXuRV4dKJ3eddkTDUDaofnCSsXHAts',
    appId: '1:12606355560:ios:00b4eaf5f5f718b109a3dd',
    messagingSenderId: '12606355560',
    projectId: 'messenger-clone-fltr',
    storageBucket: 'messenger-clone-fltr.appspot.com',
    iosBundleId: 'com.example.userChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDITrXuRV4dKJ3eddkTDUDaofnCSsXHAts',
    appId: '1:12606355560:ios:91b2c0e21525d40809a3dd',
    messagingSenderId: '12606355560',
    projectId: 'messenger-clone-fltr',
    storageBucket: 'messenger-clone-fltr.appspot.com',
    iosBundleId: 'com.example.userChatApp.RunnerTests',
  );
}
